name: Deploy Backend
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**' # ONLY triggers if files inside the Backend folder change
      - '.github/workflows/backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"