spring.application.name=newgen

# General
General.EXCEPTION_MESSAGE=Request could not be processed due to some issue. Please try again!
General.MAIL_EXCEPTION_MESSAGE=Mail servers are temporarily down. Please try again later!
Service.INVALID_PASSWORD=Please enter a valid password
Service.INVALID_ROLE=Please choose a valid role
Jwt.SECRET=${JWT_SECRET}

# Agent
Service.AGENT_ALREADY_EXISTS=Agent already exists
Service.AGENT_NOT_FOUND=Agent not found
API.AGENT_REGISTER_SUCCESS=Agent registered successfully with agent Id:
API.AGENT_LOGIN_SUCCESS=Agent logged in successfully with agent Id:

# Customer
Service.CUSTOMER_ALREADY_EXISTS=Customer already exists
Service.CUSTOMER_NOT_FOUND=Customer not found
API.CUSTOMER_REGISTER_SUCCESS=Customer registered successfully with Customer ID :
API.CUSTOMER_LOGIN_SUCCESS=Customer logged in successfully with Customer ID :

# OTP
Service.OTP_SENT_SUCCESS=OTP sent successfully for email
Service.OTP_VERIFIED_SUCCESS=OTP verified successfully for email
Service.OTP_GENERATED_SUCCESS=Generated OTP for email
Service.OTP_NOT_FOUND=OTP not found for email
Service.OTP_INVALID=Invalid OTP for email
API.SESSION_INVALID=Session Expired Or Invalid!
Service.PASSWORD_RESET_SUCCESS=Password Reset Successfully!

# Policy
Service.POLICY_NOT_FOUND=Policy not found
Service.POLICY_ALREADY_EXISTS=Policy already exists
Service.POLICY_PURCHASE_SUCCESS=Policy purchased successfully with policy ID:
Service.POLICY_RENEW_SUCCESS_WITH_PENALTY=Policy renewed successfully with penalty for policy ID:
Service.POLICY_RENEW_SUCCESS_WITHOUT_PENALTY=Policy renewed successfully without penalty for policy ID:
Service.POLICY_ACTIVE=Policy is active
Service.POLICY_LAPSED=Policy has lapsed
API.POLICY_RENEW_SUCCESS_WITH_PENALTY=Policy renewed successfully with penalty for policy ID:
API.POLICY_RENEW_SUCCESS_WITHOUT_PENALTY=Policy renewed successfully without penalty for policy ID:

# Payment
Service.PAYMENT_SUCCESS=Payment completed successfully
Service.PAYMENT_FAILED=Payment failed

# Dashboard
Service.NO_CUSTOMERS_FOUND=No customers found
Service.NO_POLICIES_FOUND=No policies found

# New Cloud URL with SSL required
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require

# Cloud Credentials
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===================================================================
# JPA & Hibernate Settings
# ===================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8765

#Spring Mail
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}