name=LoggingFile
rootLogger.level=info

# Point Default Root Logger To Both Console & Log As Fallbacks
rootLogger.appenderRefs=file,console
rootLogger.appenderRef.file.ref=LoggerAppender
rootLogger.appenderRef.console.ref=ConsoleAppender

# File Appender Configuration
appender.file.type=File
appender.file.name=LoggerAppender
appender.file.fileName=log/ErrorLog.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{dd-MMM-yyyy HH:mm:ss} %level - %m%n

# Console Appender Configuration
appender.console.name=ConsoleAppender
appender.console.type=Console
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%m%n

# Declaring Logger For Business Logic
logger.newgen_util.name=com.infy.newgen.utility
logger.newgen_util.level=DEBUG
logger.newgen_util.appenderRef.file.ref=LoggerAppender
logger.newgen_util.additivity=false

# Targets Main
logger.newgen_main.name=com.infy.newgen
logger.newgen_main.level=INFO
logger.newgen_main.appenderRef.file.ref=LoggerAppender
logger.newgen_main.additivity=false